### PR TITLE
Fix settings page and update dependencies.

### PR DESCRIPTION
**Pull request by jwetzell**
The form change was being called when the form inputs where being loaded which was triggering preferences updates which failed because the form wasn't complete.

### CODE REVIEW

**Comment by jwetzell** [comment]
Added some more small things to this 😛

**Comment by ethanmassie** [comment]
Can you update the user state so that it doesn't separate preferences from the user data? I think the issue with it not updating was because we aren't doing a deep clone of the object.  I do like the userPreferences selector though, just change it to select user.userData.preferences.

Alternatively, instead of doing a deep clone we could keep the set action for preferences as it's own action (probably better named updatePreferences since it can get set in the same action as setting the userData) and update that nested part of the state specifically.  

Does the updateUser rest call return the updated user? If so we should update our state with what it's returning rather than what was in the form.  In general we should trust what was persisted by the backend more than what was submitted.  

If you do go the deep clone route checkout lodash-es.  It's just lodash compiled for es.  Also add the @types/lodash dev dependency.  I'm not sure if deep clone is actually the best route though.

**Comment by jwetzell** [comment]
You lost me at deep cloning. there was nothing telling the user state to update so why would it? But I do see that the update call does return the whole updated user object so I'll just keep the userPreferences selector remove the setPreferences Action and just call the set user action with the callback from the updatePreferences and that should work.

**Comment by ethanmassie** [comment]
I think you will run into issues if you try to update the preferences just with the setUser action.  It will not update the deeply nested parts of the object (i.e preferences).  So, you will either need a separate action for updating that deeply nested part of the object or you will need to use deepClone from lodash or something.  Check the ngrx documentation I linked to.

I could be wrong though so go ahead and try without the deep clone or separate preferences update action.

**Comment by jwetzell** [comment]
Simply calling setUser with what is returned from the updatePreferences call seems to update the nested preferences object inside the userData and accomplish what I was trying to fix with the settings page.

**Comment by ethanmassie** [comment]
Alright cool, thanks for updating it.

**Pull request merged**
